image: ruby:2.3

# define the environment variables
variables:
  JEKYLL_ENV: production

# add bundle cache to 'vendor' & untracked files for speeding up builds
cache:
  untracked: true
  paths: 
    - vendor/

# 'bundle' all the required gems for the project
before_script:
  - bundle install --path vendor

# build and deploy the site
pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public/
    when: always
  only:
  - pages