# Site details
name:        Rosie & Jim
description: Our Digital Home
owner:       rosiejim
authors:
  - richard
  - rosie
  - rosiejim
url:         http://www.perry-online.me.uk
email:       richard@perry-online.me.uk

# Handling Reading
exclude: 
  - 'changes'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'Gruntfile.js'
  - 'node_modules'
  - 'package.json'
  - 'Rakefile'
  - 'README.md'

# Plugins
gems:
  - jekyll-mentions
  - jemoji

# Outputting
permalink:           /:categories/:title/
paginate:            10
paginate_path:       "page/:num"
timezone:            Europe/London
defaults:
  -
    scope:
      path:          ""
      type:          "posts"
    values:
      layout:        "post"
      comments:      true
  -
    scope:
      path:          "pages"
    values:
      layout:        "page"
      comments:      false

# Markdown Processors
kramdown:
  use_coderay:       true

sass:
  style:             compressed


category_dir: /

flickr:
  enabled:         yes
  cache_dir:       ./_cache/flickr
  api_key:         4389a0eb79c41ca17e149830c22fc7c2
  shared_secret:   ef41108edae962b0
  access_token:    72157641557984045-92a5dbebf3e01418
  access_secret:   1625dbdd3cf26db6
