######################################
#                                    #
#         Site Configuration         #
#                                    #
######################################

# Site details
title: Rosie & Jim
description: Our Digital Home
author: rosiejim
authors:
  - richard
  - rosie
  - rosiejim
url: https://www.perry-online.me.uk
email: richard@perry-online.me.uk

# Handling Reading
exclude: 
  - 'changes'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'LICENSE.md'
  - 'README.md'
  - 'vendor'

plugins:
  - jekyll-seo-tag
  - jemoji


######################################
#                                    #
#        Theme Configuration         #
#                                    #
######################################

# General Configuration
theme: jekyll-theme-perry
logo: /assets/images/logo.svg
meta:             
  copyright:
    year: '2009'
  powered-by: true
  hosting:          
    name: GitLab Pages
    link: //pages.gitlab.io

# Markdown Processors
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Europe/London
defaults:
  -
    scope:
      path:          ""
      type:          "posts"
    values:
      layout:        "post"
      comments:      true
  -
    scope:
      path:          "pages"
    values:
      layout:        "page"
      comments:      false


######################################
#                                    #
#        Plugin Configuration        #
#                                    #
######################################

# Jekyll SEO Tag Gem
facebook:
  app_id: 181763705182339
  admins: 286603693

twitter:
  username: richard_p2

social:
  links:
    - https://twitter.com/richard_p2
    - https://www.facebook.com/richardpperry
    - https://www.linkedin.com/in/rpperry
    - https://plus.google.com/+RichardPerry1
    - https://github.com/richardp2

google:
  analytics: UA-26085183-1

webmaster_verifications:
  google: kShm7KvCbKtxnGKHhDpje_9bPdemRwk2OLXtfjEBWEQ
